apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app.kubernetes.io/instance: chatbot2-apr25-3
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: chatbot2-apr25-3
  name: chatbot2-apr25-3
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 100Gi
